### ISSUE TITLE
Support ZEEBE_REST_ADDRESS and ZEEBE_GRPC_ADDRESS

### ISSUE THREAD

**Issue by jwulf** [camunda/camunda-8-js-sdk#137]
See: https://github.com/camunda/zeebe/issues/14126

**Comment by jwulf** [comment]
![image](https://github.com/camunda/camunda-8-js-sdk/assets/406975/1fcb9aa3-7b97-4bd3-bc36-a8630a042af8)

**Comment by hassan-alnator** [comment]
@jwulf are you currently working on this issue ?

**Comment by jwulf** [comment]
@hassan-alnator not yet. You're welcome to create a PR if you want.

**Comment by hassan-alnator** [comment]
@jwulf thank you ill work on it , just to make sure the transition is smooth I will make sure to check both variables and get display a message that ZEEBE_ADDRESS Env will be deprecated soon.

**Comment by jwulf** [comment]
Implemented via https://github.com/camunda/camunda-8-js-sdk/pull/159
