### ISSUE TITLE
HTTP Basic authentication support is missing

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-8-js-sdk#165]
## SDK Component

Camunda 8 client

## Expected Behavior

Allow to pass username and password to authenticate with HTTP Basic.

## Current Behavior

Support is missing although it is provided in zeebe-node: https://github.com/camunda-community-hub/zeebe-client-node-js/?tab=readme-ov-file#basic-auth

## Possible Solution

Port from zeebe-node

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

Required for https://github.com/camunda/camunda-modeler/pull/4233

**Comment by jwulf** [comment]
Can do. I pulled this out of the gRPC client rather than adding it across the board. Sorry! I added for my personal use case, and I didn't realise anyone else was using it.

**Comment by jwulf** [comment]
Set the following via properties or env vars: 

```
CAMUNDA_AUTH_STRATEGY=BASIC
CAMUNDA_BASIC_AUTH_USERNAME=....
CAMUNDA_BASIC_AUTH_PASSWORD=....
```

**Comment by barmac** [comment]
Thanks for fixing this so fast! :)
