### ISSUE TITLE
Add Job Update Timeout command to the JS Client

### ISSUE THREAD

**Issue by aim-dot-antares** [camunda/camunda-8-js-sdk#166]
Hello!
Please add Job Update Timeout command to the JS Client (@camunda8/sdk)

**Comment by jwulf** [comment]
https://github.com/camunda/camunda-8-js-sdk/blob/alpha/src/proto/zeebe.proto#L962

**Comment by aim-dot-antares** [comment]
Thanks for the link, Josh! 
But I can't find the function in ZeebeGrpcClient.

const zeebe = c8.getZeebeGrpcApiClient();
zeebe.updateJobTimeout

**Comment by jwulf** [comment]
@aim-dot-antares that was a note for me to help with the implementation. 

Are you using the JS SDK at the moment and need this feature?

**Comment by aim-dot-antares** [comment]
@jwulf 

I wanted to receive user tasks through a worker and set different blocking times for them. And I didn’t find a solution until I read about adding a function in the Zeebe API.

But at the moment I am considering the option of reading data about user tasks from the elastic index. In this case (as far as I understand) the TIMEOUT events do not occur. So adding a function is no longer relevant for me.

However, I thought it would be a good idea to report her absence.

**Comment by jwulf** [comment]
Available in 8.5.5 and 8.6.0. 

Documentation: https://camunda.github.io/camunda-8-js-sdk/classes/index.Zeebe.ZeebeGrpcClient.html#updateJobTimeout
