### ISSUE TITLE
Support Zeebe StreamActivatedJobs API

### ISSUE THREAD

**Issue by jwulf** [camunda/camunda-8-js-sdk#17]
## SDK Component
Zeebe

 The Zeebe Gateway has a new RPC StreamJobs to open a long-lived stream that essentially "pushes" jobs to the worker.

This obviates polling loops.

https://github.com/camunda/zeebe/issues/14152

Environment variable to enable it:

ZEEBE_CLIENT_WORKER_STREAMENABLED

See also the documentation about the general concept, including how back pressure works and can be implemented for your custom client: https://stage.docs.camunda.io/docs/next/components/concepts/job-workers/#job-streaming

**Comment by aleksander-dytko** [comment]
Hi @jwulf, do I assume correctly that this is targeted for 8.5 release?

**Comment by jwulf** [comment]
Hi @aleksander-dytko, it will probably soon come after the 8.5 release, asynchronously. There is a lot of work across the entire SDK for the 8.5 release.

**Comment by aleksander-dytko** [comment]
Thanks @jwulf. Do you know the rough timeline for this? 
The customer raised a Feature Request [here](https://jira.camunda.com/browse/SUPPORT-20947) and I wanted to provide them with an update

**Comment by aleksander-dytko** [comment]
@jwulf @akeller do we know when this item will be delivered? I wanted to update the customer in the [feature request](https://jira.camunda.com/browse/SUPPORT-20947)

**Comment by jwulf** [comment]
This feature is under development, I estimate that it will be available at the end of May. 

In the meantime, would you be able to share the current worker creation parameters? There may be some tuning that can be done with the existing long polling that could mitigate the resource exhaustion. 

Some ideas that occur to me are to extend the long poll period, and also to add a randomised offset to it so that different workers that are started at the same time do not all poll at once.

**Comment by jwulf** [comment]
@aleksander-dytko an update on the status of this. This has been more challenging than I had anticipated. My revised time to deliver support for this feature in the JS SDK is the second week of June.

**Comment by jwulf** [comment]
At the moment, this feature fails in CI against both SM and SaaS. 

On my local machine, it fails or succeeds with no discernable pattern. 

I am using Wireshark to see if I can debug it at the network level.

The stream is opened, but sometimes nothing comes over it locally. On CI, nothing comes over it. 

CI is running Ubuntu. Locally, I am running MacOS. I am installing Ubuntu locally to see what happens there.

**Comment by jwulf** [comment]
@pepopowitz and I paired on this today. This appears to be an issue with the underlying JS gRPC library. We haven't been able to isolate the circumstances surrounding the failure to get it to stably reproduce. 
 
 Today, it worked for some time, and then started failing. 
 Here is a network packet capture from Wireshark for the failing call from the JS client:
 
<img width="716" alt="Screenshot 2024-06-05 at 7 59 48 PM" src="https://github.com/camunda/camunda-8-js-sdk/assets/406975/ed001cea-dbd1-4543-8bb0-d61868ac4cd3">

The data packet that is being sent is an End Stream command. 
 
<img width="354" alt="Screenshot 2024-06-05 at 8 00 43 PM" src="https://github.com/camunda/camunda-8-js-sdk/assets/406975/78b3e258-844f-4254-9965-58d4b6d53e71">

With GRPC trace debugging turned on, this is what happens:

<img width="830" alt="Screenshot 2024-06-05 at 8 01 23 PM" src="https://github.com/camunda/camunda-8-js-sdk/assets/406975/be309fc3-3d44-42aa-8581-1627b93b8da1">

For some reason, the stream is terminated by the client immediately.

Contrast this with the network capture of the same request from the Java client: 

<img width="727" alt="Screenshot 2024-06-05 at 7 59 29 PM" src="https://github.com/camunda/camunda-8-js-sdk/assets/406975/24d669f0-9675-482e-bc6f-b3123459a94e">

**Comment by jwulf** [comment]
In the test, it needs a two second delay after starting the stream before starting a process instance.

**Comment by jwulf** [comment]
@aleksander-dytko support for the streaming jobs API is available in the latest packages: 8.5.5 and 8.6.0. 

Documentation:

https://camunda.github.io/camunda-8-js-sdk/classes/index.Zeebe.ZeebeGrpcClient.html#streamJobs
