### ISSUE TITLE
ZeebeGrpcClient.deployResource with an array of resources

### ISSUE THREAD

**Issue by TylerHAtkinson** [camunda/camunda-8-js-sdk#173]
## SDK Component
Zeebe

## Expected Behavior
Both the documentation: https://camunda.github.io/camunda-8-js-sdk/classes/index.Zeebe.ZeebeGrpcClient.html#deployResource
and the comment above `deployResource` https://github.com/camunda/camunda-8-js-sdk/blob/570d5bb27e6358343a2513719825f4d4e80933f1/src/zeebe/zb/ZeebeGrpcClient.ts#L645
indicate that we should be able to deploy multiple resources.

I would expect there to be a signature that accepts an array of resources to allow for this

## Current Behavior
All of the deployResource overloads only support a single resource, and it sends an array with only that 1 resource to the underlying `(await this.grpc).deployResourceSync({`

## Possible Solution
Either add an overload to accept an array of resources, or add a new function called `deployResources` if you want to avoid more overloads on that function, and call `(await this.grpc).deployResourceSync({` with the full array of resources

## Context (Environment)
We are trying to deploy all of our bpmns/dmns at once, ideally with the rollback feature the documentation describes if one of them in the batch fails

**Comment by jwulf** [comment]
Thanks for the suggestions @TylerHAtkinson.

I went with option B: `deployResources`.

```typescript
const result = await zbc.deployResources([
   {
      processFilename: './src/__tests__/testdata/Client-DeployWorkflow.bpmn',
   },
   {
      decisionFilename: './src/__tests__/testdata/quarantine-duration.dmn',
   },
   {
      form: fs.readFileSync('./src/__tests__/testdata/form_1.form'),
      name: 'form_1.form',
   },
])
```
