### ISSUE TITLE
`publishMessage` is not throwing an error when there isn't an active token waiting for a message

### ISSUE THREAD

**Issue by rangeranger** [camunda/camunda-8-js-sdk#202]
[publishMessage](https://camunda.github.io/camunda-8-js-sdk/classes/index.Zeebe.ZeebeGrpcClient.html#publishMessage) is not throwing an error when there isn't an active token waiting for a message.

This is the default behaviour on Camunda 7 and it is needed for us because we cannot send a success response to our clients when they publish message at a wrong time.

## SDK Component
Zeebe

## Expected Behavior
Throw an error when there isn't a token waiting for that message with that correlation key.

## Current Behavior
Doesn't throw an error.

## Context (Environment)
When our clients interact with us, we publish these messages and give a response back. Our clients are not supposed to move forward with the next steps if we return a non-success response. In this case, we cannot provide that functionality and is a hard blocker for us to launch Camunda 8.

**Comment by jwulf** [comment]
Hi @rangeranger, this is not an issue with the SDK, it's the behaviour of the system. 

Please see this issue: https://github.com/camunda/camunda/issues/16304
