### ISSUE TITLE
Tolerant edge cases in LosslessJsonParser

### ISSUE THREAD

**Issue by ryanelee** [camunda/camunda-8-js-sdk#212]
When there is a edge case in the input variable payload such as array of null elements, the recursive method `convertLosslessNumbersToNumberOrThrow` underneath the `createWorker` throws `cannot read properties of null` error.

## SDK Component
Zeebe gRPC client

## Expected Behavior
The null should be ignored and the JSON string should be serialized successfully 

## Current Behavior
The `convertLosslessNumbersToNumberOrThrow` method in `LosslessJsonParser.ts` throws out exception on the 1st line
`debug(`Parsing LosslessNumbers to numbers for ${obj.constructor.name}`)` when the `obj` is null.

Error:
`Cannot read properties of null (reading 'constructor')`

## Possible Solution
Add the null check in the `convertLosslessNumbersToNumberOrThrow` method in `LosslessJsonParser.ts`.

Add safe navigation operation on [line 223](https://github.com/camunda/camunda-8-js-sdk/blob/dd5717ea288bbc738863bdccf9ece194b8be9bbd/src/lib/LosslessJsonParser.ts#L223): 
`obj?.constructor?.name`

Add a null check before [224](https://github.com/camunda/camunda-8-js-sdk/blob/dd5717ea288bbc738863bdccf9ece194b8be9bbd/src/lib/LosslessJsonParser.ts#L224): 
`if (!obj) return obj;`

## Steps to Reproduce

1. Added a new unit test in [LosslessJsonParser.unit.spec.ts](https://github.com/camunda/camunda-8-js-sdk/blob/dd5717ea288bbc738863bdccf9ece194b8be9bbd/src/__tests__/lib/LosslessJsonParser.unit.spec.ts)
```
test('LosslessJsonParser correctly handles null objects', () => {
    const json = `{"abc": [null, null, null] }`;

    const parsedDto = losslessParse(json);

    expect(parsedDto.siuTaskComments).toMatchObject([null, null, null]); // 3 (string)
});
```
2. Run the unit test
4. The new added unit test will be failed with below error:

```
An unsafe number value was received for "abc" and no Dto mapping was specified.
    Cannot read properties of null (reading 'constructor')

      248 |     } catch (e) {
      249 |             const message = (e as Error).message
    > 250 |             throw new Error(
          |                   ^
      251 |                     `An unsafe number value was received for "${currentKey}" and no Dto mapping was specified.\n` +
      252 |                             message
      253 |             )
```

## Context (Environment)
The error will stop Zeebe gRPC client from polling activate tasks.

**Comment by jwulf** [comment]
Thanks for finding this and suggesting a fix. I've implemented it.
