### ISSUE TITLE
Job activation resolves before all jobs are retrieved

### ISSUE THREAD

**Issue by huygur** [camunda/camunda-8-js-sdk#214]
## SDK Component

activateJobs() method is not working as expected (as it is documented in the original [Zeebe API](https://docs.camunda.io/docs/apis-tools/zeebe-api/gateway-service/#activatejobs-rpc)). 

## Expected Behavior / Current Behavior
If Zeebe activates 20 jobs, I would like to access all 20 jobs.

- When I try to activate a job that doesn't exist (ex: invalid type)
     - **Expected behavior:** If I pass **5000** to requestTimeout, method should respond with 0 jobs after 5 seconds
      **Current behavior:** If I pass **5000** to requestTimeout, method does not respond / is stuck
     -  **Expected behavior:** If I pass *-1* to requestTimeout, method should respond with 0 jobs immediately
      **Current behavior:** If I pass *-1* to requestTimeout, method does not respond / is stuck
- If I have 20 process instances running on the same process, on the same flow node (a service task), and I try to activate jobs with the following parameters:

```
{
    "maxJobsToActivate": 20,
    "requestTimeout": 5000,
    "timeout": 1000,
    "type": "some-type",
    "worker": "some-worker"
}
```

**Expected behavior:** Zeebe activates 20 jobs, I get 20 jobs
**Current behavior:** Zeebe activates 20 jobs, I get 6 jobs

## Possible Solution
Currently stream is waiting for the data and resolves immediately once _some_ data is available: https://github.com/camunda/camunda-8-js-sdk/blob/dd5717ea288bbc738863bdccf9ece194b8be9bbd/src/zeebe/zb/ZeebeGrpcClient.ts#L291

Also, there is no stream.end function which makes the method stuck until there is some data.

Here is a PR: https://github.com/camunda/camunda-8-js-sdk/pull/213

## Steps to Reproduce

1.
2.
3.
4.

**Comment by jwulf** [comment]
Thank you for identifying this, and for the PR to fix it!

**Comment by jwulf** [comment]
Release 8.6.9 contains this fix.
