### ISSUE TITLE
Grpc Stream Error: 8 RESOURCE_EXHAUSTED: Received message larger than max (1752460652 vs 4194304)

### ISSUE THREAD

**Issue by DylanAhTeck-ONE** [camunda/camunda-8-js-sdk#229]
## SDK Component

Zeebe
## Expected Behavior

In the previous community project, are workers were able to poll for work
## Current Behavior

Using the new sdk and the same worker/ZB client configs, our workers are getting `Grpc Stream Error: 8 RESOURCE_EXHAUSTED: Received message larger than max (1752460652 vs 4194304)` errors

This is happening immediately after worker creation - before any process instances etc are created - for all of our workers. The received message size (1752460652) is the same for all the worker errors. 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by jwulf** [comment]
I'm not aware of a code change that will do that. The Zeebe gRPC client code is basically ported across. 

Please see this issue: https://github.com/camunda/camunda/issues/12104

If this doesn't allow you to fix it, then what we'll need for this is a Minimal Reproducer. That would be a Docker compose to start a broker setup, and a small project that triggers this error condition. With that in hand we can fix it.

**Comment by jwulf** [comment]
This seems to be caused by https://github.com/grpc/grpc-node/issues/2822

It will happen if there are no jobs available for 60 seconds on SaaS. It is a misinterpretation of the 504 timeout response. 

The workaround is to set `longPoll: 50000` in the worker constructor.

**Comment by jwulf** [comment]
Released in 8.6.17
