### ISSUE TITLE
Problem with number array parsing in Zeebe task handler

### ISSUE THREAD

**Issue by mvskvortsov** [camunda/camunda-8-js-sdk#258]
## SDK Component

Zeebe
## Expected Behavior

My input variables for ServiceTask is:
{"message":"Hello from automation","userId":null,"sendTo":[12022907,12022896,12022831]}

I need to get it in my task handler as they are.
## Current Behavior

I get this in job.variables:
{"message":"Hello from automation","userId":null,"sendTo":[{"isLosslessNumber":true,"value":"12022907"},{"isLosslessNumber":true,"value":"12022896"},{"isLosslessNumber":true,"value":"12022831"}]}

**Comment by jwulf** [comment]
Sorry that this is not working as expected for you, and thank you for reporting it. 

I have a good sense of what is going on here and how to fix it. 

Let me take a look at it tomorrow and see if I can get a fix out for you.

**Comment by mvskvortsov** [comment]
@jwulf Thank you for your answer. When might a fix be available? Today I updated package to version 8.6.13 but the problem still exists.
