### ISSUE TITLE
`publishMessage` is not throwing an error when there isn't an active token waiting for a message

### ISSUE THREAD

**Issue by aruscus** [camunda/camunda-8-js-sdk#268]
The publishMessage function in the [Camunda 8 JS SDK](https://camunda.github.io/camunda-8-js-sdk/classes/index.Zeebe.ZeebeGrpcClient.html#publishMessage) is not throwing an error when there isn't an active token waiting for a message.

This behavior was [released](https://docs.camunda.io/docs/reference/release-notes/860/#message-correlation-with-result-zeebe) with the latest Camunda 8 release (v3.6), and after testing, it's not functioning as expected.

Also, the [documentation](https://camunda.github.io/camunda-8-js-sdk/interfaces/zeebe_types.PublishMessageRequest.html#timeToLive) is incorrect. It says seconds but it is actually milliseconds.

## SDK Component
Zeebe

## Expected Behavior
The function should return a result indicating whether the message correlation was successful or not, or throw an error if there is no active token.

## Current Behavior
The function returns the same result regardless of whether the correlation is successful or not.

## Steps to Reproduce

1. Publish a message with a TTL of 0, as per the documentation. Ensure there is no event waiting for the message.

**Comment by jwulf** [comment]
This is actually a completely different API: correlateMessage. I will be publishing an updated package with this method included shortly - probably early next week.

**Comment by jwulf** [comment]
Update: the new API is only on the REST API surface, not the gRPC surface. 

At the moment, I am looking at releasing support for the REST API as an ESM module in a new package @camunda8/sdk-rest. 

@aruscus are you using CommonJS or ESM? Could you move to ESM to consume a package with this feature?

**Comment by aruscus** [comment]
@jwulf, We are currently using CommonJS but should be able to transition to ESM.

Regarding REST vs. gRPC, I’m curious about Camunda's vision on this. We currently don't use REST and rely entirely on gRPC. While we can use REST, we are trying to understand if both REST and gRPC will eventually support all features or if there is a plan to have some features exclusive to one or the other, or if everything will eventually move entirely to REST in the future.

**Comment by jwulf** [comment]
The plan at the moment is to consolidate on the REST API, which will get new features (an example is the CorrelateMessage endpoint). The gRPC API's main use case will be job streaming.

**Comment by jwulf** [comment]
There is experimental support for the Camunda 8 REST API in the latest version of the package.
