### ISSUE TITLE
Modeler API endpoints using wrong HTTP method(s)

### ISSUE THREAD

**Issue by tijmenstor** [camunda/camunda-8-js-sdk#269]
## SDK Component
Modeler

## Expected Behavior

I should be able to make use of all the API endpoints using the modeler client from this package.

## Current Behavior

Specifically, when I want to make use of `searchFiles` and `updateFile`, errors are being thrown. Looking at the code for [`searchFiles`](https://github.com/camunda/camunda-8-js-sdk/blob/bb3709348323f7b97b9e3e913c086c1c0308a325/src/modeler/lib/ModelerAPIClient.ts#L277-L288) for example, it uses `GET` as its HTTP method. The Swagger UI however indicates that this specific endpoint makes use of `POST` ([link](https://modeler.camunda.io/swagger-ui/index.html#/Files/searchFiles)).

## Possible Solution

Change the functions to make use of the correct HTTP endpoints.

## Steps to Reproduce

1. Initialize a modeler client using the latest version of this package
2. Try to make use of `searchFiles` to query the respective API endpoint
3. Receive an error like `The `GET` method cannot be used with a body`

## Context (Environment)

We are making use of the API endpoints in our deployment automation.

**Comment by jwulf** [comment]
Thanks for reporting this, and sorry that it is not working as expected. 

I will be pushing a fix for this tomorrow.
