### ISSUE TITLE
Need listeners for StreamJobs output

### ISSUE THREAD

**Issue by aruscus** [camunda/camunda-8-js-sdk#274]
## Our Setup
We initiate streaming for all workers during the startup of our NestJs microservices by calling the `streamJobs` method. Additionally, we call activateJobs for all workers during startup to handle any active jobs that were pending before streaming began.

## Summary
Recently, we encountered an issue where we needed to disable debug logs for Zeebe and the gateway, which were previously enabled to send information to Camunda Support. After deploying these resources in Kubernetes, we observed that tokens in Operate stopped progressing. We resolved this by redeploying our microservices. Based on our research, we believe that when the Zeebe gateways are redeployed, streaming is closed for existing workers, causing the gateways to stop pushing jobs to the workers.

To solve this issue and to ensure high resiliency, we need to periodically call `activateJobs` to check for active jobs. Alternatively, we could call both `createWorkers` and `streamJobs` during startup, which involves constant polling and streaming. However, this approach is inefficient.

We believe this issue could be resolved if we had listeners for the `streamJobs` output, similar to the ones you provide for `createWorkers`, to notify us when the streaming connection closes.

## SDK Component
Zeebe

## Expected Behavior
Ideally it would be great if the SDK is intelligent enough to reestablish the streaming during this scenario. (We have zero downtime in Kubernetes and when the redeployment happened for Zeebe and Gateways, it starts terminating only 1 pod at a time while starting the new pod)

## Current Behavior
The jobs are not activated and is stuck until we redeploy the microservices.

## Possible Solution
Provide listeners or solve it within the SDK.

**Comment by jwulf** [comment]
Hi @aruscus 

Yes, gateway rescheduling will disrupt the connection. Can you try the ZBClient `onConnectionError`, on appending a listener to the `connectionError` event of the ZBGrpcClient. This event is emitted when the underlying gRPC connection is disrupted. 

There are two potential issues: 

1. At some point the pure JS gRPC client (which the SDK uses) did not emit this event. This may have changed with newer versions.

2. Even the C-based gRPC client did not reliably detect the connection going away and emit the event. 

In any case, whatever connection disruption detection and notification that exists is available via the `onConnectionError` constructor parameter and the `connectionError` event of the ZBGrpcClient.
