### ISSUE TITLE
Connect to Zeebe: Received RST_STREAM with code 2

### ISSUE THREAD

**Issue by JasonYanHJ** [camunda/camunda-8-js-sdk#280]
I’m trying to deploy a self-managed Camunda8 on local k8s cluster (with kind), but I have trouble with connecting to the gateway using zeebe node-js-sdk client. Considering that the Desktop Camunda Modeler goes well, I believe there’s something wrong with my sdk config.

I can connect to my gateway and deploy BPs through Desktop Camunda Modeler using the settings as follow:
![image](https://github.com/user-attachments/assets/2e5adbd3-7ccf-4024-98f0-c7ac2d1657d3)
![image](https://github.com/user-attachments/assets/6c909e1c-b46c-4a6a-b521-f4a7ca26960e)

However, I cannot connect to it through the zeebe node-js-sdk using the similar settings. Here is my config for node-js-sdk:
```
const config: Camunda8ClientConfiguration = {
  ZEEBE_ADDRESS: "zeebe.camunda.local",
  ZEEBE_CLIENT_ID: "zeebe",
  ZEEBE_CLIENT_SECRET: "demo",
  ZEEBE_GRPC_ADDRESS: "zeebe.camunda.local",
  CAMUNDA_AUTH_STRATEGY: "OAUTH",
  CAMUNDA_OAUTH_URL:
    "http://camunda.local/auth/realms/camunda-platform/protocol/openid-connect/token",
  CAMUNDA_TASKLIST_BASE_URL: "http://camunda.local/tasklist",
  CAMUNDA_OPERATE_BASE_URL: "http://camunda.local/operate",
  CAMUNDA_OPTIMIZE_BASE_URL: "http://camunda.local/optimize",
  CAMUNDA_SECURE_CONNECTION: false,
  CAMUNDA_ZEEBE_OAUTH_AUDIENCE: "zeebe-api",
  CAMUNDA_OPERATE_OAUTH_AUDIENCE: "operate-api",
  CAMUNDA_TASKLIST_OAUTH_AUDIENCE: "tasklist-api",
  CAMUNDA_OPTIMIZE_OAUTH_AUDIENCE: "optimize-api",
  zeebeGrpcSettings: {
    ZEEBE_CLIENT_LOG_LEVEL: "DEBUG",
    ZEEBE_INSECURE_CONNECTION: true,
  },
  CAMUNDA_LOG_LEVEL: "debug",
  CAMUNDA_TENANT_ID: "",
};
```

and these are my client code outputs:
```
20:51:13.464 | zeebe |  INFO: Grpc Middleware blocking: false
20:51:13.525 | zeebe |  INFO: Middleware emits ready
20:51:18.590 | zeebe |  INFO: Set Grpc channel ready timer for 3000ms
/.../camunda-zeebe-client-ts/node_modules/@grpc/grpc-js/src/call.ts:82
  const error = new Error(message);
                ^
Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error
```

I appreciate any help you can offer. Thank you in advance!

**Comment by JasonYanHJ** [comment]
I referred to the [official nodejs-sdk doc](https://docs.camunda.io/docs/apis-tools/node-js-sdk/) and simplified the codes in the doc as follows:

```typescript
const camunda = new Camunda8(clientConfig);
const zeebe = camunda.getZeebeGrpcApiClient();
async function main() {
  const deploy = await zeebe.deployResource({
    processFilename: path.join(process.cwd(), "bpmn/process.bpmn"),
  });
}

main();
```

Before I trying to deploy a local k8s cluster, I’ve successed to deploy one without k8s (using docker-compose) and successed to connect it using the codes above with some similar ‘localhost’ settings.

Then, I followed [the official local k8s cluster tutorial](https://docs.camunda.io/docs/self-managed/setup/deploy/local/local-kubernetes-cluster/#ingress-configuration-in-camunda-8-helm-charts) and tried to switch to the k8s cluster. I modified the related address settings from 'localhost' to 'camunda.local'/'zeebe.camunda.local', but only the Desktop Modeler works and the sdk codes didn't.

What I did in Desktop Modeler is changing the 'Cluster endpoint' from 'http://localhost:26500' to 'http://zeebe.camunda.local' and changing the 'Authentication' from 'Basic' to 'OAuth'. The Modeler worked as expected (can deploy BPs to k8s cluster), but when I do the similar changes to the node-js sdk config, it didn't work and output 'RST_STREAM with code 2' which I mentioned before.

That's wierd. Hope someone could help me, thanks a lot!

**Comment by jwulf** [comment]
The error sounds like TLS is turned on by the client. Try setting: `ZEEBE_INSECURE_CONNECTION: true`.

**Comment by JasonYanHJ** [comment]
@jwulf Thanks  for respond!

I tried some possible settings and found `ZEEBE_GRPC_ADDRESS: "zeebe.camunda.local:80"` solved my problem.

I must explicitly set the proxy to 80.

**Comment by jwulf** [comment]
Great! Good to hear that you found a fix.
