### ISSUE TITLE
Add Zeebe Tasklist REST API

### ISSUE THREAD

**Issue by jwulf** [camunda/camunda-8-js-sdk#34]
The Tasklist API is moving to the Zeebe Gateway. See here: https://github.com/camunda/zeebe/issues/15622

How this is implemented in the SDK will depend on the API surface area that we expose to developers. 

It may be possible to do this with no change to the API surface area. 

This will be targeted to post-8.5.

**Comment by tg185111** [comment]
Does this mean we cannot use zeebe user tasks in 8.5 with this sdk?

**Comment by jwulf** [comment]
Migrating to Zeebe User Tasks: https://docs.camunda.io/docs/apis-tools/tasklist-api-rest/migrate-to-zeebe-user-tasks/
